# Generated by Django 4.2.9 on 2024-02-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_remove_graphic_file_type_alter_graphic_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='graphic',
            name='file_types',
            field=models.ManyToManyField(to='graphics.filetype'),
        ),
    ]
