# Generated by Django 4.2.9 on 2024-02-09 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0003_filetype_graphic_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categroies', to='graphics.category'),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='file_types',
            field=models.ManyToManyField(related_name='graphics', to='graphics.filetype'),
        ),
    ]
