# Generated by Django 4.2.9 on 2024-02-09 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_alter_graphic_category_alter_graphic_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='graphics.category'),
        ),
    ]
