# Generated by Django 4.2.9 on 2024-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0006_alter_graphic_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='file_types',
            field=models.ManyToManyField(related_name='filetypes', to='graphics.filetype'),
        ),
    ]
