# Generated by Django 4.2.9 on 2024-02-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0008_alter_graphic_file_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='file_url',
            field=models.ImageField(upload_to='graphics/'),
        ),
    ]
