# Generated by Django 4.2.9 on 2024-02-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0009_alter_graphic_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='file_url',
            field=models.FileField(upload_to='graphics/'),
        ),
    ]
